#load
load("C:/Users/Ido/My Drive/R/unchosen_mf_mb/data/model_recovery/data_mf/modelfit_like_per_trial_recovery_mf.rdata")
mf=like
load("C:/Users/Ido/My Drive/R/unchosen_mf_mb/data/model_recovery/data_mf/modelfit_like_per_trial_recovery_mb.rdata")
mb=like

load("C:/Users/Ido/My Drive/R/unchosen_mf_mb/data/model_recovery/data_mf/modelfit_like_per_trial_recovery_baseline.rdata")
baseline=like

load("C:/Users/Ido/My Drive/R/unchosen_mf_mb/data/model_recovery/data_mf/modelfit_like_per_trial_recovery_full.rdata")
full=like


#sample sums
baseline=rowMeans(baseline)
full=rowMeans(full)
mf=rowMeans(mf)
mb=rowMeans(mb)
# Convert lists to data frames
baseline_df <- data.frame(value = unlist(baseline))
full_df <- data.frame(value = unlist(full))
mf_df <- data.frame(value = unlist(mf))
mb_df <- data.frame(value = unlist(mb))

# Add a column to distinguish the datasets
baseline_df$group <- 'baseline'
full_df$group <- 'full'
mf_df$group <- 'mf'
mb_df$group <- 'mb'

# Combine the data frames
combined_data <- rbind(full_df,mf_df)

# Load the ggplot2 library
library(ggplot2)

# Create the density plot
ggplot(combined_data, aes(x = exp(value), fill = group)) +
  geom_density(alpha = 0.5) +
  labs(title = "Predictive performance on out-of-sample choices generated by MF only",
       x = "Value",
       y = "Density") +
  theme_minimal()
